version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - APP_ENV=production
      - APP_KEY=${APP_KEY}
      - DB_CONNECTION=${DB_CONNECTION}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_DATABASE=${DB_DATABASE}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
    volumes:
      - .:/var/www/html
    ports:
      - "80:80"
      - "21:21"
      - "10000-10100:10000-10100"
    command: /bin/sh -c "./setup.sh && php artisan serve --host=0.0.0.0 --port=80"

networks:
  default:
    external:
      name: coolify
